# Generated by Django 3.2.2 on 2021-05-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20)),
                ('teachername', models.CharField(max_length=20)),
                ('coursecollege', models.CharField(max_length=20)),
                ('isdrawlots', models.BooleanField(default=False)),
                ('maxnum', models.PositiveSmallIntegerField()),
                ('studentnum', models.PositiveSmallIntegerField(null=True)),
                ('introduce', models.CharField(max_length=100, null=True)),
                ('passratio', models.FloatField(null=True)),
                ('failnum', models.PositiveSmallIntegerField(null=True)),
                ('goodnum', models.PositiveSmallIntegerField(null=True)),
                ('outstandingnum', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentname', models.CharField(max_length=20)),
                ('receivename', models.CharField(max_length=20)),
                ('messagetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curcourseid', to='course_app.course')),
                ('precourseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precourseid', to='course_app.course')),
            ],
            options={
                'unique_together': {('courseid', 'precourseid')},
            },
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.SmallIntegerField()),
                ('usercollege', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.user'),
        ),
        migrations.AddField(
            model_name='select',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiveid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiveid', to='course_app.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='sentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sentid', to='course_app.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_app.user'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('studentid', 'courseid')},
        ),
        migrations.AlterUniqueTogether(
            name='select',
            unique_together={('studentid', 'courseid')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sentid', 'receiveid', 'messagetime')},
        ),
    ]
