# Generated by Django 3.2.2 on 2021-05-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20210519_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginuser',
            fields=[
                ('index', models.SmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course_app.user')),
            ],
        ),
    ]
