# Generated by Django 3.2.2 on 2021-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_loginuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='islogin',
            field=models.BooleanField(default=False),
        ),
    ]
