# Generated by Django 3.2.2 on 2021-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_delete_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagetime',
            field=models.CharField(max_length=30),
        ),
    ]
