# Generated by Django 3.2.2 on 2021-05-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_alter_message_messagetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='select',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
