# Generated by Django 3.2.2 on 2021-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_auto_20210523_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacherid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiveid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='courseid',
            field=models.CharField(max_length=20),
        ),
    ]
