# Generated by Django 3.2.2 on 2021-05-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_auto_20210523_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiveid',
            new_name='receiveid_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sentid',
            new_name='sentid_id',
        ),
    ]
