# Generated by Django 3.2.2 on 2021-05-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_auto_20210523_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
    ]
