# Generated by Django 3.2.2 on 2021-05-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_alter_student_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.user'),
        ),
    ]
