# Generated by Django 3.2.2 on 2021-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_alter_course_studentnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studentnum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
