# Generated by Django 3.2.2 on 2021-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0013_alter_course_studentnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coursename',
        ),
    ]
