# Generated by Django 3.2.2 on 2021-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0014_remove_student_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='introduce',
            field=models.CharField(default='暂无', max_length=100),
        ),
    ]
