# Generated by Django 3.2.2 on 2021-05-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0016_auto_20210523_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=20)),
                ('courseware', models.FileField(upload_to='')),
            ],
        ),
    ]
